### ISSUE TITLE
Direct hyperlink to build in Drone

### ISSUE THREAD

**Issue by shmileee** [jdamata/drone-teams#6]
Would be nice to a have a direct hyperlink to the build in Drone, so one can easily access it by clicking something in Team's message.

**Comment by jdamata** [comment]
This should already be working. Currently the pipeline checks if the DRONE_COMMIT_LINK env var is defined and includes it as a card fact.

Env var -> https://docs.drone.io/pipeline/environment/reference/drone-commit-link/
Plugin code checking for that value -> https://github.com/jdamata/drone-teams/blob/master/plugin/impl.go#L83

Can you include a step in your drone pipeline that outputs the value of DRONE_COMMIT_LINK to check if it is empty?

**Comment by jdamata** [comment]
@shmileee Found out that the drone plugin library isn't setting the value needed for stash. I added some logic to use the environment variable if its empty: https://github.com/jdamata/drone-teams/commit/ae0be04e3213ac08eb52981fbc4945f3796fefe7
